### ISSUE TITLE
Add redash as a plugin for analysis

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#1146]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/1171

Originally created by @dmor on 2019-10-22 15:58:09

---

## Task List ##

* [ ]  @dmor complete opportunity assessment
* [ ]  Feasibility discussion
* [ ]  Scope MVC
* [ ]  @dmor GO/No-GO Decision
* [ ]  @dmor If GO create epic and implementation issues

## Opportunity Assessment ##

**1. Exactly what problem will this solve? (value proposition)**

As we continue to build Meltano, we can’t be reliant on our own execution of features that already exist in the market. Our goal is to be the glue, and we aren’t significantly differentiated on analysis as a feature. It would be too expensive and take too long for us to develop this feature on our own, so we need to integrate a 3rd party solution.

**2. For whom do we solve that problem? (target market)**

For users:
* Who want to write their own queries
* Who want to build graphs and charts

For ourselves:
* We don’t need to build and maintain all these features
* We wouldn’t have to build an analysis tool from the ground up
* We wouldn’t have to create a large team to maintain and improve it
* We get all the features of Metabase
* We get to leverage Metabase documentation

**3. How big is the opportunity? (market size)**

Most Meltano users, whether on the command line or in the UI, will eventually want to produce analysis and dashboards

**4. What alternatives are out there? (competitive landscape)**

Our current Analyze experience, which is limited but works

Exporting the data that Meltano has extracted, loaded, and transformed into a third party analysis solution (Periscope, Tableau, Looker, Mode, etc.)

The risk is that if users start to rely on some other product for Analysis, they will eventually not need Meltano ELT (there is a lot of consolidation going on right now, and many dashboarding companies are moving up the stack) and won't benefit from the end-to-end pipeline management solution we are offering.

**5. Why are we best suited to pursue this? (our differentiator)**

We understand the integration points of Meltano 

**6. Why now? (market window)**

In order to get users to adopt Meltano and come back, they need to create dashboards that they want to keep leveraging over time. They need to feel like these dashboards provide crucial insights into business metrics and power business processes in their companies

**7. How will we get this product to market? (go-to-market strategy)**

Email existing users, blog posts, social media, case studies.

* [ ] @kressaty can you please add more info here? 

**8. How will we measure success/make money from this product? (metrics/revenue strategy)**

Increased MAUI

**9. What factors are critical to success? (solution requirements)**

* [ ]  @mbergeron @iroussos this is where I am going to need help to look at the integration points

### Open Questions ###

*  Can we iframe Redash as an initial solution (similar to Airflow)?
*  What is the compatibility of their language choices / stack with ours?
*  How does Redash play with git for version control?

10. Given the above, what’s the recommendation? (go or no-go)

* [ ]  @dmor TODO -- need to fill in [#9](https://gitlab.com/meltano/meltano/-/issues/9) first

**Comment by MeltyBot** [comment]
[View 21 previous comments from the original issue on GitLab](https://gitlab.com/meltano/meltano/-/issues/1171)
