### ISSUE TITLE
Consider something like 'Meltano Desktop' - An Electron app as an alternative (and possible future replacement) for the current web UI

### ISSUE THREAD

**Issue by MeltyBot** [meltano/meltano#3151]
Migrated from GitLab: https://gitlab.com/meltano/meltano/-/issues/3225

Originally created by @alexmarple on 2022-02-08 18:37:45

---

### Tasks
- [x] Add more links for research
- [ ] Add Figma files for visual research
- [ ] Add possible time table for development

### Problem to solve
This isn't really solving a problem. This is just a nice to have/Makes us look even more legit.

### Target audience
Non-command line users but really anyone and everyone. I imagine that if this gets off the ground we will have very few folks using the web app anymore (like how Slack has a webapp but nobody really uses it...)

### Further details
Meltano has so far been a CLI-first company. As we create a more robust UI, it makes sense to explore/create a desktop app that would be useful to folks who don't have any CLI experience and don't want it.

### Proposal
Leveraging Electron to use the existing webapp to build a potentially cross platform application that abstracts away the startup tasks for getting Meltano going while also having all of the bells and whistles that exist already.

### What does success look like, and how can we measure that?
Have a bug-free desktop app that builds upon the web UI experience.

### Links / references

- [Electron](https://www.electronjs.org/)
- [Vue Electron Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/)
- [Smashing Mag Article on building the above](https://www.smashingmagazine.com/2020/07/desktop-apps-electron-vue-javascript/)
- [Electron/Vue FS component](https://itnext.io/a-file-system-browser-component-for-electron-vue-js-applications-eab285fbb3cb)
- [Electron-Vue](https://simulatedgreg.gitbooks.io/electron-vue/content/en/)
- [Working with IO files in an Electron App](https://medium.com/jspoint/working-with-files-i-o-in-an-electron-application-b4d2de403f54)
- [Beginners Guide to Electron](https://medium.com/jspoint/a-beginners-guide-to-creating-desktop-applications-using-electron-824da5665047)
- [Selecting a directory in Electron](https://jaketrent.com/post/select-directory-in-electron)

**Comment by MeltyBot** [comment]
[View 5 previous comments from the original issue on GitLab](https://gitlab.com/meltano/meltano/-/issues/3225)
