### ISSUE TITLE
Incremental addoption of static typing

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#6715]
This issue will track our progress as we add or fix type annotations to the codebase.

Static type checks were recently added in CI (#6707), but most submodules are currently ignored.

Modules which need updates to pass `mypy` static type checking:

```[tasklist]
### Tasks
- [x] https://github.com/meltano/meltano/pull/6708
- [x] https://github.com/meltano/meltano/pull/6831
- [x] https://github.com/meltano/meltano/pull/8890
- [ ] `meltano.cli.*`
- [x] `meltano.core.connection_service`
- [x] `meltano.core.db`: https://github.com/meltano/meltano/pull/8902
- [ ] `meltano.core.elt_context`
- [x] `meltano.core.extract_utils`
- [x] `meltano.core.extractor`
- [x] `meltano.core.meltano_invoker`
- [x] `meltano.core.migration_service`: https://github.com/meltano/meltano/pull/8902
- [ ] `meltano.core.models`
- [x] `meltano.core.plugin_discovery_service`
- [x] `meltano.core.plugin_install_service`: https://github.com/meltano/meltano/pull/8718
- [ ] `meltano.core.plugin_invoker`
- [x] `meltano.core.plugin_test_service`
- [x] `meltano.core.project`
- [x] `meltano.core.project_add_service`: https://github.com/meltano/meltano/pull/8902
- [ ] `meltano.core.project_files`
- [x] `meltano.core.project_plugins_service`: https://github.com/meltano/meltano/pull/8902
- [ ] `meltano.core.project_settings_service`
- [x] `meltano.core.select_service`: https://github.com/meltano/meltano/pull/8720
- [x] `meltano.core.settings_service`
- [x] `meltano.core.settings_store`: https://github.com/meltano/meltano/pull/9108
- [ ] `meltano.core.sqlalchemy`
- [ ] `meltano.core.task_sets_service`
- [ ] `meltano.core.transform_add_service`
- [ ] `meltano.core.behavior.*`
- [x] `meltano.core.block.block_parser`: https://github.com/meltano/meltano/pull/9101
- [ ] `meltano.core.block.blockset`: https://github.com/meltano/meltano/pull/9110
- [ ] `meltano.core.block.extract_load`: https://github.com/meltano/meltano/pull/9110
- [ ] `meltano.core.block.future_utils`: https://github.com/meltano/meltano/pull/9110
- [ ] `meltano.core.block.ioblock`: https://github.com/meltano/meltano/pull/9110
- [ ] `meltano.core.block.plugin_command`: https://github.com/meltano/meltano/pull/9110
- [ ] `meltano.core.block.singer`: https://github.com/meltano/meltano/pull/9110
- [x] `meltano.core.compiler.*`
- [x] `meltano.core.job.*`: https://github.com/meltano/meltano/pull/8879
- [x] `meltano.core.legacy_tracking.*`
- [x] `meltano.core.logging.job_logging_service`
- [x] `meltano.core.logging.output_logger`
- [x] `meltano.core.logging.utils`
- [x] `meltano.core.m5o.*`
- [ ] `meltano.core.plugin.*`
- [ ] `meltano.core.runner.*`
- [x] `meltano.core.sql.*`
- [ ] `meltano.core.tracking.*`
- [ ] `meltano.core.utils.*`
```
