### ISSUE TITLE
Replace `flakeheaven`, `pyupgrade`, and `isort` with `ruff`

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7383]
@edgarrmondragon has proven Ruff's value and suitability across several repositories within the Meltano GitHub org.

We should be able to use it to replace `flakeheaven`, `pyupgrade`, and `isort` within the Meltano repository. This should significantly reduce the amount of time it takes for our linters to run. Additionally this will increase the number of lint issues which can be auto-fixed, and will significantly reduce the number of dev dependencies we have.

Some of the Flake8/Flakeheaven lint plugins we use are not yet supported by Ruff:
- `flake8-broken-line`, but Black handles this.
- `flake8-rst-docstrings`, but we use Markdown docstrings.
- `flake8-string-format`, but we primarily use f-strings instead of `str.format`. We use `str.format` in 4 places, and all of those should be switched to use f-strings instead (because they aren't using an `str.format`-exclusive features like unpacking an argument list into the format string).
- `flake8-typing-as-t`. We may want to open an issue https://github.com/charliermarsh/ruff requesting support for this flake8 plugin. [`flake8-import-conventions`](https://beta.ruff.rs/docs/rules/#flake8-import-conventions-icn) is supported, but it doesn't affect `from ... import ...` style import statements, only `import module as bad_alias`.
- `wemake-python-styleguide`. Personally I'm okay with losing the WPS lint rules. I find that they're just as likely to be detrimental to the quality of the code as they are to improve it. We have 452 `noqa` comments within this repository, and 344 of them are for WPS rules. Of the 136 disabled lint rules within `pyproject.toml`, 98 of them are WPS rules. There are definitely plenty of good rules we'd be losing, but the most important/impactful rules tend to find their way into other flake8 plugins and related tools.

We'll lose the Flakeheaven baseline (see https://github.com/charliermarsh/ruff/issues/1149), but Ruff can add `noqa` comments using the `--add-noqa`, so once we've switched over and addressed every new lint issue uncovered that we want to address, we can easily add a noqa comment to the remaining ones. This adds some visual noise compared to a baseline file, but has the benefit of being explicit about what rules are being ignored and where.

Ruff can also automatically remove unused noqa comments, which will make this transition easier since it saves us from having to go through 452 existing noqa comments to see which ones are no longer necessary :sweat_smile:

Ruff rule classes to enable:

```[tasklist]
### Tasks
- [x] `"A", # flake8-builtins`: https://github.com/meltano/meltano/pull/8605
- [x] `"ANN", # flake8-annotations`: https://github.com/meltano/meltano/pull/8678
- [x] `"ARG", # flake8-unused-arguments`: https://github.com/meltano/meltano/pull/8047
- [x] `"B",   # flake8-bugbear`: https://github.com/meltano/meltano/pull/7445
- [x] `"C4",  # flake8-comprehensions`: https://github.com/meltano/meltano/pull/7444
- [x] `"COM", # flake8-commas`: https://github.com/meltano/meltano/pull/7435
- [x] `"D", # pydocstyle/flake8-docstrings`: https://github.com/meltano/meltano/pull/8679
- [x] `"DTZ", # flake8-datetime`: https://github.com/meltano/meltano/pull/8265
- [x] `"E",   # pycodestyle (error)`: https://github.com/meltano/meltano/pull/7401/
- [x] `"EM",  # flake8-errmsg`: https://github.com/meltano/meltano/pull/8445
- [x] `"F",   # pyflakes`: https://github.com/meltano/meltano/pull/7401/
- [x] `"FBT", # flake8-boolean-trap`: https://github.com/meltano/meltano/pull/8677
- [x] `"ICN", # flake8-import-conventions`: https://github.com/meltano/meltano/pull/8673
- [x] `"I",   # isort`: https://github.com/meltano/meltano/pull/7409
- [x] `"INP", # flake8-no-pep420`: https://github.com/meltano/meltano/pull/8613
- [x] `"ISC", # flake8-implicit-str-concat`: https://github.com/meltano/meltano/pull/7434
- [x] `"N",   # pep8-naming`: https://github.com/meltano/meltano/pull/8415
- [x] `"PGH", # pygrep-hooks`: https://github.com/meltano/meltano/pull/8606
- [x] `"PIE", # flake8-pie`: https://github.com/meltano/meltano/pull/8467
- [x] `"PT",  # flake8-pytest-style`: https://github.com/meltano/meltano/pull/7473
- [x] `"PTH", # flake8-use-pathlib`: https://github.com/meltano/meltano/pull/8674
- [x] `"Q",   # flake8-quotes`: https://github.com/meltano/meltano/pull/8467
- [x] `"RET", # flake8-return`: https://github.com/meltano/meltano/pull/8461
- [x] `"RSE", # flake8-raise`: https://github.com/meltano/meltano/pull/7446
- [x] `"RUF", # Ruff-specific rules`: https://github.com/meltano/meltano/pull/8672
- [x] `"SIM", # flake8-simplify`: https://github.com/meltano/meltano/pull/7447
- [x] `"T10", # flake8-debugger`: https://github.com/meltano/meltano/pull/8467
- [x] `"T20", # flake8-print`: https://github.com/meltano/meltano/pull/8452
- [x] `"TCH", # flake8-type-checking`: https://github.com/meltano/meltano/pull/8294
- [x] `"TID", # flake8-tidy-imports`: https://github.com/meltano/meltano/pull/7493
- [x] `"UP",  # pyupgrade`: https://github.com/meltano/meltano/pull/7413
- [x] `"W",   # pycodestyle (warning)`: https://github.com/meltano/meltano/pull/7401/
- [x] `"YTT", # flake8-2020`: https://github.com/meltano/meltano/pull/8628
- [x] https://github.com/meltano/meltano/pull/8671
- [ ] https://github.com/meltano/meltano/pull/8680
```

**Comment by aaronsteers** [comment]
Very excited to see this. And a great write-up, thank you!

> Ruff can add noqa comments using the --add-noqa, so once we've switched over and addressed every new lint issue uncovered that we want to address, we can easily add a noqa comment to the remaining ones. This adds some visual noise compared to a baseline file, but has the benefit of being explicit about what rules are being ignored and where.

In theory at least, I actually this a lot. 👍 Especially combined with:

> Ruff can also automatically remove unused noqa comments, which will make this transition easier since it saves us from having to go through 452 existing noqa comments to see which ones are no longer necessary 😅

**Comment by edgarrmondragon** [comment]
@nkclemson has expressed interest in tackling the missing rules, so he might start opening PRs.
