### ISSUE TITLE
Unify the Cloud CLI with the Meltano CLI

### ISSUE THREAD

**Issue by WillDaSilva** [meltano/meltano#7959]
In the Core Guild meeting on 2023-07-27, we decided to simplify Meltano by unifying the Cloud CLI with the regular Meltano CLI. This comes at some notable costs, such as no longer having a lightweight way to interact with Meltano Cloud, but continuing to support this separation increases complexity and imposes a maintenance burden that we cannot justify.

Unifying these applications breaks down into the following tasks:
```[tasklist]
### Tasks
- [ ] https://github.com/meltano/meltano/issues/7578
- [x] Make [this issue](https://github.com/meltano/meltano/issues/7645) apply to Meltano in general, rather than the Cloud CLI in particular
- [x] Update the installation instructions in the docs to remove any mention of installing the Cloud CLI independently by specifying the subdirectory in the our git repository to install from
- [x] Remove `src/cloud-cli/pyproject.toml`, and other files which are only present to support the Cloud CLI as a standalone application
- [x] Move the Cloud CLI tests under the root tests directory, and update all references to `src/cloud-cli/tests/`
- [x] Move the Cloud CLI source code into `src/meltano/`
```
