### ISSUE TITLE
Missing dependency wheels tracker

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/meltano#8495]
```[tasklist]
### Tasks
- [ ] [`atomicwrites`](https://pypi.org/project/atomicwrites/): It's pure Python so that's good, but it's unmaintained so we'll never have wheels for it. Author says: "Python 3 has os.replace and os.rename which probably do well enough of a job for most usecases."
- [ ] [`psutil`](https://pypi.org/project/psutil/): Doesn't have wheels for all Python versions and platforms. Related issues: https://github.com/giampaolo/psutil/issues?q=is%3Aopen+is%3Aissue+label%3Awheels
- [ ] [`google-crc32c`](https://pypi.org/project/google-crc32c/): https://github.com/googleapis/python-crc32c/issues/178
```

## Why?

Building wheels takes time and might require native dependencies and compilers, so it's preferable for Meltano's dependencies to have wheels for all its supported Python versions and most common platforms.

## Notes

1. This is not an extensive list, just a quick summary of the wheels that need to be [built in our Docker images](https://github.com/meltano/meltano/actions/workflows/docker_publish.yml). If you know of more missing wheels, please leave a comment on this issue.

**Comment by edgarrmondragon** [comment]
I've marked `psutil` since the latest (6.0.0) has a few more wheels: https://github.com/giampaolo/psutil/blob/master/HISTORY.rst#600-2024-06-18
